"""add trust tables

Revision ID: c643bc42d092
Revises: d69b8a698c4c
Create Date: 2026-10-01 09:16:34.211151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c643bc42d092'
down_revision = 'd69b8a698c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('product', 'seller', 'transaction', 'user', name='report_target_type'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'investigating', 'resolved', 'rejected', name='report_status'), nullable=False),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_handled_by'), ['handled_by'], unique=False)
        batch_op.create_index('ix_reports_reporter_id', ['reporter_id'], unique=False)
        batch_op.create_index('ix_reports_status', ['status'], unique=False)
        batch_op.create_index('ix_reports_target', ['target_type', 'target_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_rating', sa.Integer(), nullable=False),
    sa.Column('seller_rating', sa.Integer(), nullable=False),
    sa.Column('shipping_rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('published', 'hidden', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_buyer_id', ['buyer_id'], unique=False)
        batch_op.create_index('ix_reviews_product_id', ['product_id'], unique=False)
        batch_op.create_index('ix_reviews_seller_id', ['seller_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_seller_id')
        batch_op.drop_index('ix_reviews_product_id')
        batch_op.drop_index('ix_reviews_buyer_id')

    op.drop_table('reviews')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_target')
        batch_op.drop_index('ix_reports_status')
        batch_op.drop_index('ix_reports_reporter_id')
        batch_op.drop_index(batch_op.f('ix_reports_handled_by'))

    op.drop_table('reports')
    # ### end Alembic commands ###
